import { StyleSheet } from 'react-native';

const SignupStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#fff',
    padding: 20,
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 40,
  },
  backText: {
    fontSize: 16,
    color: '#000',
    fontWeight: '500',
  },
  logo: {
    width: 110,
    height: 110,
    resizeMode: 'contain',
    marginBottom: 18,
    alignSelf: 'center',
    position: 'relative',
    zIndex: 2,
    backgroundColor: 'transparent',
    borderRadius: 0,
    shadowColor: 'transparent',
    elevation: 0,
  },
  title: {
    color: '#111',
    fontSize: 26,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 18,
    marginTop: 10,
    letterSpacing: 0.5,
  },
  label: {
    color: '#111',
    marginTop: 10,
    marginBottom: 5,
    fontWeight: '600',
  },
  required: {
    color: 'red',
    fontWeight: 'bold',
  },
  errorText: {
    color: 'red',
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
  },
  input: {
    borderColor: '#bbb',
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 12,
    backgroundColor: '#fff',
    color: '#111',
    marginBottom: 10,
    fontSize: 16,
  },
  dropdown: {
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 8,
    backgroundColor: '#fff',
    marginBottom: 8,
  },
  button: {
    backgroundColor: '#000',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 30,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
  },
  divider: {
    height: 1,
    backgroundColor: '#444',
    width: '100%',
    marginTop: 20,
    marginBottom: 10,
  },
  langSwitchRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 18,
    marginBottom: 30,
  },
  langSimpleBtn: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#000',
  },
  langActiveBtn: {
    backgroundColor: '#000',
  },
  langSimpleText: {
    color: '#000',
    fontSize: 15,
    fontWeight: 'bold',
  },
  langActiveText: {
    color: '#fff',
  },
  profileContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    marginTop: 8,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: '#ccc',
    marginBottom: 8,
    backgroundColor: '#eee',
  },
  imagePickerText: {
    color: '#888',
    fontSize: 16,
    textAlign: 'center',
  },
  dobRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  picker: {
    flex: 1,
    height: 44,
    backgroundColor: '#f4f4f4',
    borderRadius: 10,
    marginHorizontal: 4,
    borderColor: '#bbb',
    borderWidth: 1.5,
    marginBottom: 10,
  },
  positionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginVertical: 8,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  errorBorder: {
    borderColor: 'red',
    borderWidth: 1,
  },
  positionButton: {
    backgroundColor: '#f4f4f4',
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 16,
    margin: 2,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  selectedButton: {
    backgroundColor: '#000',
    borderColor: '#000',
  },
  positionButtonText: {
    color: '#000',
    fontSize: 15,
    fontWeight: '500',
  },
  selectedButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  // Additional styles for all possible signup screens/fields
  parentContainer: {
    flexGrow: 1,
    backgroundColor: '#fff',
    padding: 20,
  },
  academyContainer: {
    flexGrow: 1,
    backgroundColor: '#fff',
    padding: 20,
  },
  agentContainer: {
    flexGrow: 1,
    backgroundColor: '#fff',
    padding: 20,
  },
  parentTitle: {
    color: '#111',
    fontSize: 26,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 18,
    marginTop: 10,
    letterSpacing: 0.5,
  },
  academyTitle: {
    color: '#111',
    fontSize: 26,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 18,
    marginTop: 10,
    letterSpacing: 0.5,
  },
  agentTitle: {
    color: '#111',
    fontSize: 26,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 18,
    marginTop: 10,
    letterSpacing: 0.5,
  },
  parentInput: {
    borderColor: '#bbb',
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 12,
    backgroundColor: '#fff',
    color: '#111',
    marginBottom: 10,
    fontSize: 16,
  },
  academyInput: {
    borderColor: '#bbb',
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 12,
    backgroundColor: '#fff',
    color: '#111',
    marginBottom: 10,
    fontSize: 16,
  },
  agentInput: {
    borderColor: '#bbb',
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 12,
    backgroundColor: '#fff',
    color: '#111',
    marginBottom: 10,
    fontSize: 16,
  },
  parentLabel: {
    color: '#111',
    marginTop: 10,
    marginBottom: 5,
    fontWeight: '600',
  },
  academyLabel: {
    color: '#111',
    marginTop: 10,
    marginBottom: 5,
    fontWeight: '600',
  },
  agentLabel: {
    color: '#111',
    marginTop: 10,
    marginBottom: 5,
    fontWeight: '600',
  },
  parentButton: {
    backgroundColor: '#000',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 30,
  },
  academyButton: {
    backgroundColor: '#000',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 30,
  },
  agentButton: {
    backgroundColor: '#000',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 30,
  },
  parentButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
  },
  academyButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
  },
  agentButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
  },
});

export default SignupStyles;
